import type { HierarchyMap } from "@docscript/types";

export const hierarchy: HierarchyMap = {
  document: null,
  section: [
    "heading",
    "paragraph",
    "text",
    "list",
    "table",
    "image",
    "divider",
    "columns",
    "quote",
    "codeBlock",
    "hyperlink",
    "header",
    "footer",
    "pageBreak",
  ],
  columns: [
    "heading",
    "paragraph",
    "text",
    "list",
    "table",
    "image",
    "quote",
    "codeBlock",
    "hyperlink",
  ],
  paragraph: ["text"],
  list: ["item"],
  item: [
    "text",
    "paragraph",
    "heading",
    "list",
    "image",
    "quote",
    "codeBlock",
    "hyperlink",
  ],
  header: null,
  footer: null,
  heading: [],
  text: [],
  image: [],
  divider: [],
  pageBreak: [],
  table: [],
  hyperlink: [],
  quote: [],
  codeBlock: [],
};
